### ISSUE TITLE
Could you please provide the source code for preprocessing the dataset SemEval 2018 Task 7.1?

### ISSUE THREAD

**Issue by vhientran** [helloeve/mre-in-one-pass#10]
Hi @helloeve ,

If possible, could you please provide the source code for preprocessing the dataset SemEval 2018 Task 7.1? Since the original dataset is in the format XML, I hope you give it for me, as I would like to process the dataset SemEval 2018 Task 7.2. Thanks so much for your consideration.

**Comment by helloeve** [comment]
Hi, I realize the data pre-processing code is not within the repo and I no longer have it after I leave my formal company:disappointed:
