### ISSUE TITLE
Error when running Training (MRE) example ( refer in README.md)

### ISSUE THREAD

**Issue by luluchow100** [helloeve/mre-in-one-pass#2]
Error imformation:
INFO:tensorflow:Error recorded from evaluation_loop: Can not squeeze dim[1], expected a dimension of 1, got 12 for 'remove_squeezable_dimensions/Squeeze' (op: 'Squeeze') with input shapes: [?,12].
在调用示例中的多关系抽取时做evaluation时的报错，training时没报错，请问该如何解决？

**Comment by helloeve** [comment]
@luluchow100 I was not able to reproduce the error. Did you use the MRE predicting command(https://github.com/helloeve/mre-in-one-pass#predicting-mre)? Btw I am not sure if that's an issue from the tennsorflow version, just for reference that I am using tensorflow `1.12.0`.
