### ISSUE TITLE
Unable to find the entities from the predicted result

### ISSUE THREAD

**Issue by kedir** [helloeve/mre-in-one-pass#3]
Hi, 
I have successfully trained the model and did prediction, but I couldn't get the entities along with the relationship predicted. I was wondering which entities from the sentence that the predicted relationship is connecting to. Thanks.

**Comment by helloeve** [comment]
@kedir Please refer to https://github.com/helloeve/mre-in-one-pass/blob/master/data/semeval2018/single/SemEval.train.tsv for the entity location and relation type. Each line should contain 4 numbers which refer to entity1_start_index, entity1_end_index, entity2_start_index, entity2_end_index
