### ISSUE TITLE
[Hyperparameter Inquiry] Can't Reproduce ACE05 Results

### ISSUE THREAD

**Issue by zhijing-jin** [helloeve/mre-in-one-pass#4]
Hi Haoyu,

Nice work on this MRE one-pass! I noticed that the commands in README.md are for SemEval 2018. Do you know what are the commands that you run ACE05 with? (We are especially curious about the hyperparameters.)

Thank you in advance for your information!

Best,
Zhijing

**Comment by helloeve** [comment]
The ACE dataset is using the same set of hyper parameter as SemEval except for the number of epochs is 15 instead. However, due to the nature of the randomness of BERT finetuning, we simply run all experiment for 5 times and pick up the best performed one.
