### ISSUE TITLE
Unable to locate the entity aware self attention code 

### ISSUE THREAD

**Issue by VishalPallagani** [helloeve/mre-in-one-pass#6]
I am trying to implement just the entity aware self-attention module of the paper and I cannot locate it in the run_classifier.py code. I will be grateful if someone can point me at the self-attention implementation code so I can get my work started.
Thanks in advance.

**Comment by helloeve** [comment]
@VishalPallagani please check the implementation in modeling.py for the entity aware self-attention model - https://github.com/helloeve/mre-in-one-pass/blob/master/modeling.py#L560-L764
